version: 2.1
jobs:
  build-test:
    docker:
      - image: circleci/node:20
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run test
      - run: npm run build
workflows:
  node-tests:
    jobs:
      - build-test
